spring:
  application:
    name: app
  ssl:
    bundle:
      pem:
        lets-encrypt:
          keystore:
            certificate: 'file:/app/certs/fullchain.pem'
            private-key: 'file:/app/certs/privkey.pem'
aws:
  region: us-east-1
  s3:
    bucket-name: thb-cc-app-us-east-1
  dynamodb:
    table-name: quotes
server:
  port: 8443
  ssl:
    bundle: 'lets-encrypt'
