name: deploy

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    env:
      WORKDIR: 'app'
      IMAGE_NAME: index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/app
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: set up jdk 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: test and package application
        run: mvn clean package

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: log into docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: run trivy scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: push image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: install cosign
        uses: sigstore/cosign-installer@v4.0.0

      - name: keyless cosign
        run: |
          cosign sign --yes ${{ env.IMAGE_NAME }}@${{ steps.push.outputs.digest }}

      - name: copy compose file to ec2
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: 'docker-compose.yaml'
          target: ${{ env.WORKDIR }}

      - name: deploy on ec2 using ssh
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -euo pipefail

            cosign verify ${{ env.IMAGE_NAME }}@${{ steps.push.outputs.digest }} \
              --certificate-identity-regexp "https://github.com/${{ github.repository }}/.github/workflows/deploy.yaml@.*" \
              --certificate-oidc-issuer "https://token.actions.githubusercontent.com"

            cd ${{ env.WORKDIR }}
            echo "IMAGE=${{ env.IMAGE_NAME }}@${{ steps.push.outputs.digest }}" > .env
            docker compose up -d --remove-orphans
