name: sshtest

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    env:
      WORKDIR: 'app'
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/app
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: copy compose file to ec2
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: 'docker-compose.yaml'
          target: ${{ env.WORKDIR }}
      - name: deploy on ec2 using ssh
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ env.WORKDIR }}
            echo "IMAGE=${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" > .env
            docker compose up -d --remove-orphans
